### PR TITLE
Removing streaming (and updating circuit-fuses)

### PR DESCRIPTION
**Pull request by stjohnjohnson**
Per https://github.com/screwdriver-cd/screwdriver/issues/135

Blocked on https://github.com/screwdriver-cd/executor-base/pull/16

### CODE REVIEW

**Comment by d2lam** [comment]
Reran the build to pull in the latest base.

LGTM 👍

**Comment by Filbird** [comment]
This line should probably be changed as well:

> This executor plugin extends the [executor-base-class], and provides methods to start jobs and stream logs

**Comment by nkatzman** [comment]
when you address filbert's comment 👍

**Comment by petey** [comment]
👍

**Pull request merged**
